version: "3.9"

services:
  web:
    container_name: u_web
    restart: always
    build:
      context: .
    ports:
      - 3000:3000
    networks:
      - upy-web-network

  nginx:
    container_name: u_web_nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
    - web
    networks:
      - upy-web-network
  
networks:
  upy-web-network:
    driver: bridge